[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.zip', 'php82Extensions.bcmath', 'php82Extensions.gd', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.intl', 'php82Extensions.dom', 'php82Extensions.fileinfo']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-scripts']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan migrate --force && php artisan filament:assets && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT'