[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.zip', 'php83Extensions.bcmath', 'php83Extensions.gd', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.intl', 'php83Extensions.dom', 'php83Extensions.fileinfo']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-scripts']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan migrate --force && php artisan filament:assets && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT'