[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs_20', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.zip', 'php83Extensions.bcmath', 'php83Extensions.gd', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.intl', 'php83Extensions.dom', 'php83Extensions.fileinfo']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-scripts', 'npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'mkdir -p storage/app/livewire-tmp && mkdir -p storage/app/public && php artisan config:clear && php artisan migrate --force && php artisan storage:link && chmod -R 777 storage && chmod -R 775 bootstrap/cache public && php artisan serve --host=0.0.0.0 --port=$PORT'